<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LogActivitiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('log_activities')->delete();
        
        \DB::table('log_activities')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 12:50:17',
                'updated_at' => '2025-09-29 12:50:17',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 13:34:09',
                'updated_at' => '2025-09-29 13:34:09',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'logout',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 13:34:22',
                'updated_at' => '2025-09-29 13:34:22',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 13:35:00',
                'updated_at' => '2025-09-29 13:35:00',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 13:42:33',
                'updated_at' => '2025-09-29 13:42:33',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 13:50:08',
                'updated_at' => '2025-09-29 13:50:08',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'logout',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 13:50:29',
                'updated_at' => '2025-09-29 13:50:29',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 18:09:18',
                'updated_at' => '2025-09-29 18:09:18',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Tambah Menu',
                'model_type' => 'Modules\\Settings\\Models\\Menu',
                'model_id' => '1',
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 18:22:44',
                'updated_at' => '2025-09-29 18:22:44',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Tambah Menu',
                'model_type' => 'Modules\\Settings\\Models\\Menu',
                'model_id' => '2',
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 18:23:25',
                'updated_at' => '2025-09-29 18:23:25',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Tambah Menu',
                'model_type' => 'Modules\\Settings\\Models\\Menu',
                'model_id' => '3',
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 18:23:53',
                'updated_at' => '2025-09-29 18:23:53',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Tambah Menu',
                'model_type' => 'Modules\\Settings\\Models\\Menu',
                'model_id' => '4',
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 18:24:32',
                'updated_at' => '2025-09-29 18:24:32',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Tambah Menu',
                'model_type' => 'Modules\\Settings\\Models\\Menu',
                'model_id' => '5',
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 18:25:05',
                'updated_at' => '2025-09-29 18:25:05',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 19:33:49',
                'updated_at' => '2025-09-29 19:33:49',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 20:49:06',
                'updated_at' => '2025-09-29 20:49:06',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 20:50:08',
                'updated_at' => '2025-09-29 20:50:08',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 20:50:40',
                'updated_at' => '2025-09-29 20:50:40',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 20:51:03',
                'updated_at' => '2025-09-29 20:51:03',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 20:53:10',
                'updated_at' => '2025-09-29 20:53:10',
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 21:02:29',
                'updated_at' => '2025-09-29 21:02:29',
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'logout',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 21:02:41',
                'updated_at' => '2025-09-29 21:02:41',
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 21:06:13',
                'updated_at' => '2025-09-29 21:06:13',
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 21:06:30',
                'updated_at' => '2025-09-29 21:06:30',
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 21:23:29',
                'updated_at' => '2025-09-29 21:23:29',
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 21:29:50',
                'updated_at' => '2025-09-29 21:29:50',
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 21:31:04',
                'updated_at' => '2025-09-29 21:31:04',
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 21:32:36',
                'updated_at' => '2025-09-29 21:32:36',
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 21:55:52',
                'updated_at' => '2025-09-29 21:55:52',
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'logout',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 22:00:17',
                'updated_at' => '2025-09-29 22:00:17',
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 22:00:37',
                'updated_at' => '2025-09-29 22:00:37',
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'logout',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 22:00:51',
                'updated_at' => '2025-09-29 22:00:51',
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 22:02:21',
                'updated_at' => '2025-09-29 22:02:21',
            ),
            32 => 
            array (
                'id' => 33,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'logout',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 22:02:28',
                'updated_at' => '2025-09-29 22:02:28',
            ),
            33 => 
            array (
                'id' => 34,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 22:03:53',
                'updated_at' => '2025-09-29 22:03:53',
            ),
            34 => 
            array (
                'id' => 35,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'logout',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 22:03:59',
                'updated_at' => '2025-09-29 22:03:59',
            ),
            35 => 
            array (
                'id' => 36,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 22:04:25',
                'updated_at' => '2025-09-29 22:04:25',
            ),
            36 => 
            array (
                'id' => 37,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'logout',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 22:04:31',
                'updated_at' => '2025-09-29 22:04:31',
            ),
            37 => 
            array (
                'id' => 38,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 22:05:20',
                'updated_at' => '2025-09-29 22:05:20',
            ),
            38 => 
            array (
                'id' => 39,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'PostmanRuntime/7.48.0',
                'deleted_at' => NULL,
                'created_at' => '2025-09-29 22:23:53',
                'updated_at' => '2025-09-29 22:23:53',
            ),
            39 => 
            array (
                'id' => 40,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-30 14:05:15',
                'updated_at' => '2025-09-30 14:05:15',
            ),
            40 => 
            array (
                'id' => 41,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'logout',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-30 14:05:24',
                'updated_at' => '2025-09-30 14:05:24',
            ),
            41 => 
            array (
                'id' => 42,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-30 14:05:34',
                'updated_at' => '2025-09-30 14:05:34',
            ),
            42 => 
            array (
                'id' => 43,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'logout',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-30 14:06:44',
                'updated_at' => '2025-09-30 14:06:44',
            ),
            43 => 
            array (
                'id' => 44,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-30 14:07:12',
                'updated_at' => '2025-09-30 14:07:12',
            ),
            44 => 
            array (
                'id' => 45,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'logout',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-30 14:07:26',
                'updated_at' => '2025-09-30 14:07:26',
            ),
            45 => 
            array (
                'id' => 46,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-09-30 14:13:10',
                'updated_at' => '2025-09-30 14:13:10',
            ),
            46 => 
            array (
                'id' => 47,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Tambah Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '1',
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:09:37',
                'updated_at' => '2025-10-01 05:09:37',
            ),
            47 => 
            array (
                'id' => 48,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Update Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '1',
                'changes' => '{
"role_name": {
"from": "System Adminstrator ( IT )",
"to": "System Adminstrator ( IT ) Update"
},
"updated_by": {
"from": "unknown",
"to": "udin"
},
"updated_at": {
"from": "2025-10-01T05:09:37.000000Z",
"to": "2025-10-01 05:10:33"
}
}',
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:10:33',
                'updated_at' => '2025-10-01 05:10:33',
            ),
            48 => 
            array (
                'id' => 49,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Tambah Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '2',
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:13:07',
                'updated_at' => '2025-10-01 05:13:07',
            ),
            49 => 
            array (
                'id' => 50,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Hapus Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '1',
                'changes' => '{
"id": 1,
"role_name": "System Adminstrator ( IT ) Update",
"created_by": "udin",
"updated_by": "udin",
"deleted_by": "udin",
"deleted_at": "2025-10-01T05:14:43.000000Z",
"created_at": "2025-10-01T05:09:37.000000Z",
"updated_at": "2025-10-01T05:14:43.000000Z"
}',
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:14:43',
                'updated_at' => '2025-10-01 05:14:43',
            ),
            50 => 
            array (
                'id' => 51,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Hapus Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '2',
                'changes' => '{
"id": 2,
"role_name": "HRD (Sumber Daya Manusia)",
"created_by": "udin",
"updated_by": "unknown",
"deleted_by": "udin",
"deleted_at": "2025-10-01T05:15:13.000000Z",
"created_at": "2025-10-01T05:13:07.000000Z",
"updated_at": "2025-10-01T05:15:13.000000Z"
}',
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:15:13',
                'updated_at' => '2025-10-01 05:15:13',
            ),
            51 => 
            array (
                'id' => 52,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Tambah Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '3',
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:38:32',
                'updated_at' => '2025-10-01 05:38:32',
            ),
            52 => 
            array (
                'id' => 53,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Hapus Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '3',
                'changes' => '{
"id": 3,
"role_name": "s",
"created_by": "udin",
"updated_by": "unknown",
"deleted_by": "udin",
"deleted_at": "2025-10-01T05:38:54.000000Z",
"created_at": "2025-10-01T05:38:32.000000Z",
"updated_at": "2025-10-01T05:38:54.000000Z"
}',
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:38:54',
                'updated_at' => '2025-10-01 05:38:54',
            ),
            53 => 
            array (
                'id' => 54,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Tambah Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '4',
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:44:15',
                'updated_at' => '2025-10-01 05:44:15',
            ),
            54 => 
            array (
                'id' => 55,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Tambah Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '5',
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:44:32',
                'updated_at' => '2025-10-01 05:44:32',
            ),
            55 => 
            array (
                'id' => 56,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Update Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '4',
                'changes' => '{
"role_name": {
"from": "OWNER",
"to": "OWNER update"
},
"updated_by": {
"from": "unknown",
"to": "udin"
},
"updated_at": {
"from": "2025-10-01T05:44:15.000000Z",
"to": "2025-10-01 05:45:28"
}
}',
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:45:28',
                'updated_at' => '2025-10-01 05:45:28',
            ),
            56 => 
            array (
                'id' => 57,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Update Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '5',
                'changes' => '{
"role_name": {
"from": "System Adminstrator ( IT )",
"to": "System Adminstrator ( IT ) Update2"
},
"updated_by": {
"from": "unknown",
"to": "udin"
},
"updated_at": {
"from": "2025-10-01T05:44:32.000000Z",
"to": "2025-10-01 05:46:03"
}
}',
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:46:03',
                'updated_at' => '2025-10-01 05:46:03',
            ),
            57 => 
            array (
                'id' => 58,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Update Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '5',
                'changes' => '{
"role_name": {
"from": "System Adminstrator ( IT ) Update2",
"to": "System Adminstrator ( IT ) Update1"
},
"updated_at": {
"from": "2025-10-01T05:46:03.000000Z",
"to": "2025-10-01 05:47:42"
}
}',
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:47:42',
                'updated_at' => '2025-10-01 05:47:42',
            ),
            58 => 
            array (
                'id' => 59,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'logout',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:51:15',
                'updated_at' => '2025-10-01 05:51:15',
            ),
            59 => 
            array (
                'id' => 60,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'login',
                'model_type' => NULL,
                'model_id' => NULL,
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:51:25',
                'updated_at' => '2025-10-01 05:51:25',
            ),
            60 => 
            array (
                'id' => 61,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Tambah Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '6',
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:51:41',
                'updated_at' => '2025-10-01 05:51:41',
            ),
            61 => 
            array (
                'id' => 62,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Tambah Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '7',
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:53:15',
                'updated_at' => '2025-10-01 05:53:15',
            ),
            62 => 
            array (
                'id' => 63,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Tambah Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '8',
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:56:24',
                'updated_at' => '2025-10-01 05:56:24',
            ),
            63 => 
            array (
                'id' => 64,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Hapus Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '4',
                'changes' => '{
"id": 4,
"role_name": "OWNER update",
"created_by": "udin",
"updated_by": "udin",
"deleted_by": "udin",
"deleted_at": "2025-10-01T05:56:32.000000Z",
"created_at": "2025-10-01T05:44:15.000000Z",
"updated_at": "2025-10-01T05:56:32.000000Z"
}',
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 05:56:32',
                'updated_at' => '2025-10-01 05:56:32',
            ),
            64 => 
            array (
                'id' => 65,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Tambah Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '9',
                'changes' => NULL,
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 06:03:55',
                'updated_at' => '2025-10-01 06:03:55',
            ),
            65 => 
            array (
                'id' => 66,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Update Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '5',
                'changes' => '{
"role_name": {
"from": "System Adminstrator ( IT ) Update1",
"to": "System Adminstrator ( IT ) Update0"
},
"updated_at": {
"from": "2025-10-01T05:47:42.000000Z",
"to": "2025-10-01 06:34:30"
}
}',
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 06:34:30',
                'updated_at' => '2025-10-01 06:34:30',
            ),
            66 => 
            array (
                'id' => 67,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Update Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '8',
                'changes' => '{
"role_name": {
"from": "OWNER1",
"to": "OWNER14"
},
"updated_by": {
"from": "unknown",
"to": "udin"
},
"updated_at": {
"from": "2025-10-01T05:56:24.000000Z",
"to": "2025-10-01 06:37:03"
}
}',
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 06:37:03',
                'updated_at' => '2025-10-01 06:37:03',
            ),
            67 => 
            array (
                'id' => 68,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Update Roles',
                'model_type' => 'Modules\\Settings\\Models\\Roles',
                'model_id' => '6',
                'changes' => '{
"updated_by": {
"from": "unknown",
"to": "udin"
},
"updated_at": {
"from": "2025-10-01T05:51:41.000000Z",
"to": "2025-10-01 06:38:04"
}
}',
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 06:38:04',
                'updated_at' => '2025-10-01 06:38:04',
            ),
            68 => 
            array (
                'id' => 69,
                'user_id' => 1,
                'username' => 'udin',
                'activity' => 'Update Menu',
                'model_type' => 'Modules\\Settings\\Models\\Menu',
                'model_id' => '3',
                'changes' => '{
"parent_id": {
"from": null,
"to": "2"
},
"updated_by": {
"from": "unknown",
"to": "udin"
},
"updated_at": {
"from": "2025-09-29T18:23:53.000000Z",
"to": "2025-10-01 07:59:34"
}
}',
                'ip_address' => '127.0.0.1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
                'deleted_at' => NULL,
                'created_at' => '2025-10-01 07:59:34',
                'updated_at' => '2025-10-01 07:59:34',
            ),
        ));
        
        
    }
}